config/routes.rb
Rails.application.routes.draw do
  get 'posts/index'
  get 'posts/new'
  get 'posts/create'
  resources :moderable_models, only: %i[index new create]
  resources :posts, only: %i[index new create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/moderable.rb
module Moderable
  extend ActiveSupport::Concern

  included do
    before_save :moderator

    def moderator
      I18n.available_locales = [:en]
      string_to_be_sent = format_string_with_attributes
      remove_accent = I18n.transliterate(string_to_be_sent)
      url = URI("https://moderation.logora.fr/predict?text=#{remove_accent}")
      response = Net::HTTP.get_response(url)
      result = JSON.parse(response.body)
      return unless result['prediction']['0'] < 0.90

      self.is_accepted = true
    end

    def format_string_with_attributes
      self.class.attribute_names.map do |attribute|
        send(attribute)
      end.join(' ')
    end
  end

  class_methods do
    def moderate(*attributes)
      @attribute_names = attributes
    end

    def attribute_names
      @attribute_names || []
    end
  end
end

app/models/moderable_model.rb
class ModerableModel < ApplicationRecord
  include Moderable
  moderate :content

  validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  include Moderable
  moderate :body

  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/moderable_models_controller.rb
class ModerableModelsController < ApplicationController
  def index
    @moderable_models = ModerableModel.all
  end

  def new
    @moderable_model = ModerableModel.new
  end

  def create
    @moderable_model = ModerableModel.new(moderable_model_params)

    if @moderable_model.save
      redirect_to moderable_models_path, status: :created
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def moderable_model_params
    params.require(:moderable_model).permit(:is_accepted, :content)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to posts_path, status: :created
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def post_params
    params.require(:post).permit(:is_accepted, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def display_autorized_content(content, status)
    status ? content : "#{content} : It can be restricted"
  end
end

app/helpers/moderable_models_helper.rb
module ModerableModelsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AutomaticModerator</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/moderable_models/create.html.erb
<h1>ModerableModels#create</h1>
<p>Find me in app/views/moderable_models/create.html.erb</p>

app/views/moderable_models/index.html.erb
<div class="container">
  <h1>ModerableModels</h1>
  <%= link_to 'Add a content', new_moderable_model_path %>
  <ul>
    <% @moderable_models.each do |text| %>
      <li class="<%= text.is_accepted ? "" : "red-text" %>"><%= display_autorized_content(text.content, text.is_accepted) %></li>
    <% end %>
  </ul>
</div>

app/views/moderable_models/new.html.erb
<h1>ModerableModels</h1>



<%= form_with(model: ModerableModel) do |form| %>
  <%= form.text_field :content %>
  <%= form.submit "Search" %>
<% end %>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/index.html.erb
<div class="container">
  <h1>Posts</h1>
  <%= link_to 'Add a content', posts_new_path %>
  <ul>
    <% @posts.each do |text| %>
      <li class="<%= text.is_accepted ? "" : "red-text" %>"><%= display_autorized_content(text.body, text.is_accepted) %></li>
    <% end %>
  </ul>
</div>

app/views/posts/new.html.erb
<h1>Posts</h1>


<%= form_with(model: Post) do |form| %>
  <%= form.text_field :body %>
  <%= form.submit "Search" %>
<% end %>